### ISSUE TITLE
Push Error

### ISSUE THREAD

**Issue by Hatuna** [daikikatsuragawa/clasp-action#6]
Trying to use the action, but getting this error, does any1 knows how to solve it?

```bash
Run daikikatsuragawa/clasp-action@v1.0.1
/usr/bin/docker run --name e1cc5172726b56add94e218e34c05e664cb352_caa02e --label e1cc51 --workdir /github/workspace --rm -e INPUT_ACCESSTOKEN -e INPUT_IDTOKEN -e INPUT_REFRESHTOKEN -e INPUT_CLIENTID -e INPUT_CLIENTSECRET -e INPUT_SCRIPTID -e INPUT_COMMAND -e INPUT_ROOTDIR -e INPUT_DESCRIPTION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e 
GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -
e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e 
ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v 
"/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v 
"/home/runner/work/_temp/_github_workflow":"/github/workflow" -v 
"/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v 
"/home/runner/work/slick/slick":"/github/workspace" e1cc51:72726b56add94e218e34c05e664cb352  "***" "***" "***" 
"***" "***" "***" "" "push" ""
ENOENT: no such file or directory, open '/github/workspace/appsscript.json'
```

here's the action i have:
```yml
name: Apps Script CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy-apps-Script:
    runs-on: ubuntu-latest
    steps:
      - uses: daikikatsuragawa/clasp-action@v1.0.1
        with:
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          idToken: ${{ secrets.ID_TOKEN }}
          refreshToken: ${{ secrets.REFRESH_TOKEN }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          scriptId: ${{ secrets.SCRIPT_ID }}
          command: 'push'

 ```

All files (appscript.json, code.js and .clasp.json) lives in the root folder, and the action is in .github/workflows
