### ISSUE TITLE
ENOENT: no such file or directory, open '/appsscript.json'

### ISSUE THREAD

**Issue by isaiahdaviscom** [daikikatsuragawa/clasp-action#9]
I am passing `GitHub Secrets` for all required fields of this `Action`.

The `Action` is run on changes to the `main` branch.

The `main` branch structure has the `Action` main.yml file under `/.github/workflows`.

When the main.yml file is executed at runtime the following error occurs:

ENOENT: no such file or directory, open '/appsscript.json'

The `/appscript.json` file is located at the root directory.

**Comment by alex-galey** [comment]
This is how I achieved  autodeploying to GAS :

Github workflow - deploy.yml
```
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    if: ${{ github.actor != 'dependabot' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install npm packages
      run: npm install

    - name: Create clasp.json
      env:
        SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
      run: echo '{"scriptId":"'$SCRIPT_ID'","rootDir":"dist"}' > .clasp.json

    - name: Create folder structure
      run: mkdir -p /home/runner

    - name: Create clasprc.json
      env:
        CLASPRC: ${{ secrets.CLASPRC }}
      run: echo "$CLASPRC" > /home/runner/.clasprc.json
  
    - name: Deploy
      run: npm run deploy
```

Scripts in package.json : 
```
  "scripts": {
    "build": "webpack",
    "upload": "npx clasp push -f",
    "deploy": "npm run build && npm run upload",
  }
```

With clasp has a dev dependency
